### ISSUE TITLE
wrong definition 

### ISSUE THREAD

**Issue by HoshyarKarimi** [bit-orbit/TheSecretBit#29]
[سرعت خواندن فایل از ورودی در حالت عادی به 512 بایت در ثانیه محدود شده است.](https://bit-orbit.github.io/the-secret-bit/posts/dd/dd/#%D8%B3%D8%B1%D8%B9%D8%AA-%D8%AE%D9%88%D8%A7%D9%86%D8%AF%D9%86-%D8%A7%D8%B2-%D9%88%D8%B1%D9%88%D8%AF%DB%8C)

Not actually. **bs** is an acronym of Block Size. `dd` works with block devices. It even assumes the file as block device. Its default block size is [512 bytes](https://docs.oracle.com/cd/E19455-01/805-7228/6j6q7uf21/index.html) that means it reads chunks of the device in the 512 bytes units, not less and more. when you pass a bs value for example 4096k to dd as a **bs** value, you tell `dd` to read every 4096kb as a block. Also it is not just about reading. **bs** is used for both read and write. The block size itself is what filesystem set to be the minimum working space. Linux block size is typically 4096 bytes which is called internal fragmentation. That is if even you make a 2 byte file, the filesystem allocates 4kb  for that file. The minimum block size for dd is 512 bytes. when you use your desired bs value for dd, it reads or writes that date in the chunks of your desired value. So this is a good practice to use multiples of 512 as bs value like, 512, 1024, 2048 etc. There is also another block size called disk block size which is controlled by disk controller.   when you format your disk, the new file system takes care how to map and use the underlying disk block size in an efficient way. So 

"اندازه بلوک در  حالت عادی 512 بایت است" 

is more accurate.

**Comment by shabane** [comment]
درست شد
