### ISSUE TITLE
shebang

### ISSUE THREAD

**Issue by HoshyarKarimi** [bit-orbit/TheSecretBit#30]
https://bit-orbit.github.io/the-secret-bit/fundamentals/shebang/shebang/
It is not a good idea to use shebang this way. it is hard coded. For example:` #!/bin/bash` or `#!/bin/python3`
What if there is no bash or python binary? What if our binaries be under `/usr/local/bin/` ?  It just fails. the best practice is always use env for shebang is scripts, like: `#!/usr/bin/env bash` or `#!/usr/bin/env python3`. This way you always sure you choose right directory to look for binaries. because it is defined in user's environment.

**Comment by shabane** [comment]
سلام. من کامنت رو فارسی می‌ذارم چون کتاب کاملا فارسی هست.
 کاملا درست می‌گید، این قسمت رو باید به عنوان یه یه نکته اضافه کرد و توی مثال اصلاح‌ش کرد. ممنونم بابت اینکه زمان گذاشتی و کتاب رو خواندی. و این ایشو خیلی برای من ارزشمند هست.
 
. اشکالی داره من ای‌دی تلگرامتو داشته باشم؟

**Comment by shabane** [comment]
done
