### ISSUE TITLE
معرفی در خبرنامه برای آشنایی بقیه با این کتاب خوب

### ISSUE THREAD

**Issue by ohmydevops** [bit-orbit/TheSecretBit#32]
سلام. خوشحال میشم اگر تمایل داشتید در خبرنامه هفتگی ما کتابی که درست کردید رو معرفی کنید. 
https://newsletter.softwaretalks.ir/

**Comment by shabane** [comment]
سلام. خیلی ممنونم بابت این پیشنهاد عالی. کتاب دچار چند مشکل هست که بعد از رفع کردنشون حتما با اجازه‌تون به خبر نامه می‌فرستم.
بسیار ممنونم.
