### ISSUE TITLE
پروانهٔ مخزن

### ISSUE THREAD

**Issue by ekm507** [bit-orbit/TheSecretBit#47]
درود!
از این که این کتاب را نوشته‌اید سپاسگزارم.

نکته‌ای دربارهٔ پروانهٔ کتاب هست که خدمت شما عرض می‌کنم.
در فایل README.md این مخزن دربارهٔ مجوز کتاب چنین جمله‌ای را نوشته‌اید:
« استفاده از این کتاب آزاد هست، اما فروش کتاب به صورت چاپ شده و یا نسخه‌های کامپیوتری مثل pdf, ebook منع شده.»
اما در بخش پروانهٔ مخزن، آن را CC-0 قرار داده‌اید که مطابق با جملهٔ بالا نیست.
به‌منظور جلوگیری از فروش کتاب با حفظ آزادی مطالعه، انتشار و گسترش، باید از پروانهٔ CC-BY-SA-NC استفاده شود.
این پروانه آزادی‌های دریافت و ارسال و هم‌چنین ویرایش کتاب را به افراد می‌دهد با دو شرط زیر:
- کتاب باید با همین پروانه منتشر شود.(share-alike)
- کتاب باید رایگان بماند. (non-commercial)

با سپاس

**Comment by shabane** [comment]
سلام، ممنونم بابت تذکرتون، تغییرش دادم.
