### ISSUE TITLE
df

### ISSUE THREAD

**Issue by Rahimz** [bit-orbit/TheSecretBit#55]
---
title: "df"
date: 2023-02-08T04:25:34+03:30
draft: false
tags: [
'df',
'disk free',
'disk usage'
]
---

<div dir='rtl'>

### فهرست

> - [مقدمه](#مقدمه)
> - [بررسی تمام فضاهای مانت شده](#بررسی-تمام-فضاهای-مانت-شده)
> - [بررسی یک فایل سیستم خاص](#بررسی-یک-فایل-سیستم-خاص)
> - [بررسی یک فایل سیستم حاوی یک فایل](#بررسی-یک-فایل-سیستم-حاوی-یک-فایل)
> - [دیدن تمام فایل سیستم ها](#دیدن-تمام-فایل-سیستم-ها)
> - [تعیین مقیاس نمایش](#تعیین-مقیاس-نمایش)
> - [دیدن مقیاس به صورت ساده شده](#دیدن-مقیاس-به-صورت-ساده-شده)
> - [مقیاس 1000](#مقیاس-1000)
> - [نمایش آی نودها](#نمایش-آی-نودها)
> - [تعیین سایز بلوک](#تعیین-سایز-بلوک)
> - [نمایش فایل سیستم های لوکال](#نمایش-فایل-سیستم-های-لوکال)
> - [نتایج بدون سینک کردن](#نتایج-بدون-سینک-کردن)
> - [تعیین فیلدهای خروجی](#تعیین-فیلدهای-خروجی)
> - [نتایج بر اساس POSIX](#نتایج-بر-اساس-POSIX)
> - [دیدن نتایج به همراه سینک کردن](#دیدن-نتایج-به-همراه-سینک-کردن)
> - [محاسبه مجموع فضاها](#محاسبه-مجموع-فضاها)
> - [نمایش فضاهای یک نوع فایل سیستم](#نمایش-فضاهای-یک-نوع-فایل-سیستم)
> - [نمایش ستون نوع فایل سیستم](#نمایش-ستون-نوع-فایل-سیستم)
> - [حذف یک فایل سیستم خاص از نتایج](#حذف-یک-فایل-سیستم-خاص-از-نتایج)
> - [واحدهای نمایش](#واحدهای-نمایش)
> - [Author or Authors:](#author-or-authors)

---

### مقدمه

ابزار df برای بررسی فضای خالی یا فضای استفاده شده در یک فایل سیستم لینوکس استفاده می‌شود.

ساختار کلی این دستور به شکل زیر است:

<div dir='ltr'>

```
$ df [option] ... [FILE] ...
```

</div>

---

### بررسی تمام فضاهای مانت شده

اگر دستور df بدون هیچ آرگومانی استفاده شود لیستی را از فضاهای موجود در تمام فایل سیستم‌هایی که در حال حاضر مانت شده‌اند، نشان می‌دهد.

باید توجه داشته باشید که این دستور، فایل سیستم‌های مانت نشده را نشان نمی‌دهد.

<div dir='ltr'>

```
$ df

# Filesystem     1K-blocks      Used Available Use% Mounted on
# tmpfs            1589124      2688   1586436   1% /run
# /dev/nvme0n1p6  60373924  44709612  12571784  79% /
# tmpfs            7945612     41424   7904188   1% /dev/shm
# tmpfs               5120         4      5116   1% /run/lock
# /dev/nvme0n1p8  79407872  52876308  22452156  71% /home
# /dev/nvme0n1p1     98304     33879     64425  35% /boot/efi
# tmpfs            1589120       156   1588964   1% /run/user/1000
# /dev/sda3      958786348 901281808   8727580 100% /media/rahim/makhzan
```
</div>

---

### بررسی یک فایل سیستم خاص

وارد کردن نام و آدرس فایل سیستم مانت شده:

<div dir='ltr'>

```
$ df /dev/sda3

# Filesystem     1K-blocks     Used Available Use% Mounted on
# /dev/sda3      958786348 901281808   8727580 100% /media/rahim/makhzan
```
</div>

---

### بررسی یک فایل سیستم حاوی یک فایل

اگر یک فایل به دستور df  داده شود اطلاعات فایل سیستمی را می‌دهد که شامل این فایل خاص باشد. برای این کار کافی است که مسیر فایل را جلوی این دستور اضافه کنید:

<div dir='ltr'>

```
$ df sample.txt

# Filesystem     1K-blocks     Used Available Use% Mounted on
# /dev/nvme0n1p8  79407872 52873308  22455156  71% /home
```
</div>

چون این فایل در دایرکتوری home قرار دارد، نتیجه نمایش داده شده همان نتیجه‌ای است که در مثال اول در ردیف پنجم نتایج، لیست شده بود 

---

### دیدن تمام فایل سیستم ها

**-a, --all**

تمام انواع فایل سیستم‌ها (حتی با سایز صفر) را هم نشان می‌دهد

<div dir='ltr'>

```
$ df -a

# Filesystem     1K-blocks     Used Available Use% Mounted on
# sysfs                  0         0         0    - /sys
# proc                   0         0         0    - /proc
# udev             7910236         0   7910236   0% /dev
# devpts                 0         0         0    - /dev/pts
# tmpfs            1589124      2692   1586432   1% /run
# /dev/nvme0n1p6  60373924  44717800  12563596  79% /
...
```
</div>

---

### تعیین مقیاس نمایش

**-B, --block-size=SIZE**

تمام اندازه‌ها را بر اساس مقیاس مشخص شده در  SIZE نشان می‌دهد:

<div dir='ltr'>

```
$ df df -B M

# Filesystem     1M-blocks     Used Available Use% Mounted on
# tmpfs              1552M      3M     1550M   1% /run
# /dev/nvme0n1p6    58959M  43670M    12270M  79% /
# tmpfs              7760M     18M     7742M   1% /dev/shm
...
```
</div>

آرگومان SIZE یک واحد اختیاری است که اگر به صورت 10K استفاده شود بر اساس ضرایب 1024 است و اگر به صورت KB استفاده شود بر اساس ضرایب 1000 خواهد بود. پیشوندهای باینری ماننند KiB=B هم قابل استفاده هستند.

---

### دیدن مقیاس به صورت ساده شده

**-h, --human-readable**

سایزها را بر اساس  ضرایب 1024 نشان می‌دهد (مانند 1023M)

<div dir='ltr'>

```
$ df -h

# Filesystem      Size  Used Avail Use% Mounted on
# tmpfs           1.6G  2.7M  1.6G   1% /run
# /dev/nvme0n1p6   58G   43G   12G  79% /
# tmpfs           7.6G   18M  7.6G   1% /dev/shm

```
</div>

---

### مقیاس 1000

**-H, --si**

نتایج را بر اساس ضرایب 1000 نشان می‌دهد (مانند 1.1G):

<div dir='ltr'>

```
$ df -H

# Filesystem      Size  Used Avail Use% Mounted on
# tmpfs           1.7G  2.8M  1.7G   1% /run
# /dev/nvme0n1p6   62G   46G   13G  79% /
# tmpfs           8.2G   22M  8.2G   1% /dev/shm
...
```
</div>

---

### نمایش آی نودها

**-i, --inodes**

لیستی از اطلاعات inodeها را به جای اطلاعات بلوک‌ها نمایش  می‌دهد:

<div dir='ltr'>

```
$ df -i
# Filesystem       Inodes   IUsed    IFree IUse% Mounted on
# tmpfs           1986403    1496  1984907    1% /run
# /dev/nvme0n1p6  3842720 1869070  1973650   49% /
# tmpfs           1986403      68  1986335    1% /dev/shm
...
```
</div>

---

### تعیین سایز بلوک

**-k**

مانند آن است که سایز واحد نمایش را به صورت --block-size=1K تعریف کنیم:

<div dir='ltr'>

```
$ df -k

# Filesystem     1K-blocks      Used Available Use% Mounted on
# tmpfs            1589124      2692   1586432   1% /run
# /dev/nvme0n1p6  60373924  44717860  12563536  79% /
# tmpfs            7945612     21448   7924164   1% /dev/shm
...
```
</div>

---

### نمایش فایل سیستم های لوکال

**-l, --local**

لیست ننایج را به فایل سیستم‌های لوکال محدود می‌کند:

<div dir='ltr'>

```
$ df -l
# Filesystem     1K-blocks      Used Available Use% Mounted on
# tmpfs            1589124      2692   1586432   1% /run
# /dev/nvme0n1p6  60373924  44717864  12563532  79% /
# tmpfs            7945612     18376   7927236   1% /dev/shm
```
</div>

---

### نتایج بدون سینک کردن

**--no-sync**

قبل از دریافت اطلاعات سینک را انجام نمی‌دهد (به صورت پیشفرض این گزینه فعال است).

---

### تعیین فیلدهای خروجی

**--output[=FIELD_LIST]**

فرمت خروجی را مشخص می‌کند. اگر مقداری برای آن تعریف نشود تمام فیلدها را نشان می‌دهد:

<div dir='ltr'>

```
$ df --output=source,avail

# Filesystem        Avail
# tmpfs           1586432
# /dev/nvme0n1p6 12563520
# tmpfs           7927236
```
</div>

مقدارهای معتبر برای فیلدها موارد زیر هستند:

<div dir='ltr'>

```
'source', 'fstype', 'itotal', 'iused', 'iavail', 
'ipcent', 'size', 'used', 'avail', 'pcent' and 'target' 
```
</div>

---

### نتایج بر اساس POSIX

**-P,- -portability**

از فرمت POSIX برای نشان دادن نتایج استفاده می‌کند:

<div dir='ltr'>

```
$ df -P

# Filesystem     1024-blocks      Used Available Capacity Mounted on
# tmpfs              1589124      2692   1586432       1% /run
# /dev/nvme0n1p6    60373924  44717876  12563520      79% /
# tmpfs              7945612     18376   7927236       1% /dev/sh
```
</div>

---

### دیدن نتایج به همراه سینک کردن

**--sync**

قبل از گرفتن اطلاعات سینک انجام می‌دهد.

---

### محاسبه مجموع فضاها

**--total**

تمام مقادیر ناچیز را حذف می‌کند و یک مقدار مجموع هم در آخر نتایج محاسبه می‌کند:

<div dir='ltr'>

```
$ df --total

# Filesystem      1K-blocks      Used Available Use% Mounted on
# tmpfs             1589124      2692   1586432   1% /run
# /dev/nvme0n1p6   60373924  44717880  12563516  79% /
# tmpfs             7945612     18376   7927236   1% /dev/shm
# tmpfs                5120         4      5116   1% /run/lock
# /dev/nvme0n1p8   79407872  52871212  22457252  71% /home
# /dev/nvme0n1p1      98304     33879     64425  35% /boot/efi
# tmpfs             1589120       148   1588972   1% /run/user/1000
# /dev/sda3       958786348 901281812   8727576 100% /media/rahim/makhzan
# total          1109795424 998926003  54920525  95% -
```
</div>

---

### نمایش فضاهای یک نوع فایل سیستم

**-t, --type=TYPE**

نتایج را به یک نوع خاص از فایل سیستم محدود می‌کند:

<div dir='ltr'>

```
$ df -t tmpfs   

# Filesystem     1K-blocks  Used Available Use% Mounted on
# tmpfs            1589124  2692   1586432   1% /run
# tmpfs            7945612 18376   7927236   1% /dev/shm
# tmpfs               5120     4      5116   1% /run/lock
# tmpfs            1589120   148   1588972   1% /run/user/1000
```
</div>

---

### نمایش ستون نوع فایل سیستم

**-T, --print-type**

نوع فایل سیستم را نیز نشان می‌دهد:

<div dir='ltr'>

```
$ df -T

# Filesystem     Type  1K-blocks      Used Available Use% # Mounted on
# tmpfs          tmpfs   1589124      2692   1586432   1% /run
# /dev/nvme0n1p6 ext4   60373924  44717888  12563508  79% /
# tmpfs          tmpfs   7945612     18376   7927236   1% /dev/shm
```
</div>

---

### حذف یک فایل سیستم خاص از نتایج

**-x, --exclude-type=TYPE**

یک نوع خاص از فایل سیستم را از نتایج حذف می‌کند:

<div dir='ltr'>

```
$ df -x tmpfs

# Filesystem     1K-blocks      Used Available Use% Mounted on
# /dev/nvme0n1p6  60373924  44717888  12563508  79% /
# /dev/nvme0n1p8  79407872  52874604  22453860  71% /home
# /dev/nvme0n1p1     98304     33879     64425  35% /boot/efi
```
</div>

---

### واحدهای نمایش

دستور
df
به صورت پیشفرض از 
1 K blocks 
برای نمایش واحد استفاده می‌کند.

واحد مورد نظر یا از گزینه 
–block-size
و یا اولین واحد مشخص شده در یکی از متغیرهای محیطی
DF_BLOCK_SIZE, BLOCKSIZE AND BLOCK_SIZE
برداشت شده و استفاده می‌شود.

بلوک سایز به ترتیب یکی از واحدهای زیر را می‌تواند داشته باشد:

**K** as in Kilo, **M**, **G**, **T**, **P**, **E**, **Z**, **Y**

---

</div>

Author or Authors:

- *[Rahim](https://github.com/rahimz)* | **<rahim.django.projects@gmail.com>**

**Comment by shabane** [comment]
سلام، بابت فصل که اضافه کردین خیلی ممنونم ازت.
یکی از بهترین نگارش هایی هست که تا الان انجام شده.
تنها یک مورد رو اگر ممکنه اضافه کنید،
قسمت دوم "بررسی یک فایل سیستم خاص" رو تغییر بدین و بجای "نام فایل" بنویسید "مسیر فایل".

و اینکه فایل سیستم (دامی) رو من درک نکردم.

بازم ممنون ازت (:

**Comment by Rahimz** [comment]
سلام 
موارد را اصلاح کردم.

عبارت مربوط به دامی را از man df برداشت کرده بودم که ظاهرا خیلی عبارت دقیقی نیست در نتیجه حذفش کردم.
