### ISSUE TITLE
فهرست برنامه با تغییر فایل نیاز به تغییر دستی دارد

### ISSUE THREAD

**Issue by arashatt** [bit-orbit/TheSecretBit#57]
فهرست برنامه با تغییر فایل نیاز به تغییر دستی دارد. مثلا اگر یک title جدید بخواهیم اضافه کنیم باید به طور دستی فهرست را هم تغییر دهیم
راه حل این میتونه باشه که از قابلیت خود cupper استفاده کنیم:
---
toc:True
---

**Comment by shabane** [comment]
مثلا فهرست tools رو میگی؟

مثلا: https://bit-orbit.github.io/the-secret-bit/tools/

**Comment by arashatt** [comment]
[image: image.png]
یه pr هم زدم در این رابطه. عکسی هم که میبینی مربوط به پروژه cupperه که
میبینی فهرست رو با یه خط کد تولید کرده.
البته یک اشکال داره این روش:
توی فایل تولید شده جای فهرست می نویسه table of contents که ما فکر کنم اینو
نمی خواییم

**Comment by arashatt** [comment]
https://github.com/zwbetz-gh/cupper-hugo-theme/blob/87e1a8608f44d46f6cc34fc54a4ddadbd2999433/i18n/en.yaml#L16
برای مشکلی که گفتم این خط باید عوض بشه.

**Comment by arashatt** [comment]
<div dir='rtl'>
فکر کنم منظورم از فهرست رو بعد رسوندم. 


عکسی  که میبینی مربوط به پروژه
 cupperه 
میبینی فهرست رو با یه خط کد تولید کرده.
 یک فصل رو اینجوری تغییر دادم در این
[pr](https://github.com/bit-orbit/the-secret-bit/pull/58)
البته یک اشکال داره این روش:
توی فایل تولید شده جای فهرست می نویسه 
table of contents 
که ما فکر کنم همچین چیزی رو  نمی خواییم
</div>

![unnamed](https://user-images.githubusercontent.com/55944526/217785243-13edc00d-b916-4543-9fab-9c2c55523da8.png)

**Comment by arashatt** [comment]
https://github.com/zwbetz-gh/cupper-hugo-theme/blob/87e1a8608f44d46f6cc34fc54a4ddadbd2999433/i18n/en.yaml#L16
برای مشکلی که گفتم این خط باید عوض بشه.

**Comment by shabane** [comment]
عه چه خوب، من ندیده بودم، تست می‌کنم مرسی
