### ISSUE TITLE
مشکل: فهرست فارسی از چپ به راست چاپ می شود.

### ISSUE THREAD

**Issue by arashatt** [bit-orbit/TheSecretBit#59]
پس از فعال کردن table of contents متوجه می شویم که از چپ به راست جدول را چاپ می کند.

می توانیم با تغییر دادن این [فایل](https://github.com/zwbetz-gh/cupper-hugo-theme/blob/87e1a8608f44d46f6cc34fc54a4ddadbd2999433/layouts/partials/toc.html) همانند تصویر با اضافه کردن  (خط ۳ و ۶) مشکل را حل کنیم
![image](https://user-images.githubusercontent.com/55944526/217886768-b73c0424-3051-417b-80da-4feb3f337985.png)

قبل از اعمال تغییرات:
![image](https://user-images.githubusercontent.com/55944526/217887959-1f2f654c-de77-4855-9450-47f7aa8ea271.png)

بعد از اعمال تغیییرات:
![image](https://user-images.githubusercontent.com/55944526/217887819-81f43c9d-255b-4659-aa33-bc0e72654d23.png)

**Comment by shabane** [comment]
تنها با یک چیزی که مشکل دارم اینه که این تیبل رو بخام اضافه کنم باید تمامی فصل های دیگه رو ادیت کنم :/
یکم سخته، علاوه به این تیبل خودمون قشنگ تر نیست؟ یه block quote داره،
نظر خودت چیه؟

**Comment by arashatt** [comment]
خوب البته من با یک خط کد زدن که  تازه با اضافه شدن هر قسمت خودشو آپدیت می کنه موافق ترم. اگر بحث سر قشنگیه میتونیم بریم کد تم رو عوض کنیم که به شکلی که ما میخواییم کار کنه.
فکر کنم نوشته بودی ۵۴ تا فصل بیشتر نیست که میشه واسه هر کدومشون رفت پاک کرد اون قسمت فهرستو.

**Comment by arashatt** [comment]
اینو من تغییر دادم. جدولی که میبینی با toc زده شده:
![image](https://user-images.githubusercontent.com/55944526/218031009-00e41be0-dcf4-4fa4-b9c2-45af6378b5e0.png)
با جدول های قبلی مو نمی زنه. بازم مشکلی بود بیان کن که من رفعش کنم:)
![image](https://user-images.githubusercontent.com/55944526/218031822-d7553a6f-efc4-421c-91df-acc552fa27f6.png)

**Comment by shabane** [comment]
خب این خیلی خوبه! 
باید تم رو فورک کنیم و تغییر بدیم پس،
بذار من دعوتت می‌کنم به ارگان

**Comment by arashatt** [comment]
باشه خیلی ممنون
