### ISSUE TITLE
tree

### ISSUE THREAD

**Issue by mehrnaz-shahi** [bit-orbit/TheSecretBit#66]
<div dir='rtl'>

### فهرست

> - [مقدمه](#مقدمه)
> -  [کاربردها](#کاربردها)
> - [نحوه نصب](#نحوه-نصب)
> - [توضیح برخی از آپشن ها](#توضیح-برخی-از-آپشن-ها)

---

### مقدمه
دستور "tree" در لینوکس یکی از ابزارهای پرکاربرد برای نمایش ساختار فایل‌ها و دایرکتوری‌ها به صورت درختی در خط فرمان است.

![image](https://github.com/bit-orbit/the-secret-bit/assets/91686230/0651327b-0bca-4c1f-89e1-be98a7ac7660)
---

### کاربردها
برخی از کاربردهای این دستور عبارتند از:

- نمایش ساختار درختی دایرکتوری فعلی: با اجرای دستور "tree" در دایرکتوری فعلی، شما می‌توانید یک نمای کلی از ساختار فایل‌ها و دایرکتوری‌های موجود در آن را مشاهده کنید.

- نمایش ساختار درختی یک دایرکتوری خاص: با استفاده از دستور "tree" و دادن مسیر دایرکتوری به عنوان ورودی، می‌توانید ساختار درختی آن دایرکتوری را نمایش دهید.
`$ tree ادرس دایرکتوری مدنظر`

- محاسبه فضای استفاده شده توسط دایرکتوری: با استفاده از گزینه "du--"، دستور "tree" می‌تواند مجموع فضای استفاده شده توسط فایل‌های داخل دایرکتوری را نمایش دهد.
`$tree --du`

- نمایش فایل‌های پنهان: با استفاده از گزینه "a-"، دستور "tree" تمام فایل‌ها و دایرکتوری‌های پنهان را نیز نمایش می‌دهد.

`$tree -a`

- محدود کردن سطح نمایش: با استفاده از گزینه "-L" و تعیین یک عدد، می‌توانید سطح نمایش درخت را محدود کنید و تنها یک مجموعه خاص از دایرکتوری‌ها را نمایش دهید.
به عنوان مثال، فرض کنید دایرکتوری "/home/user/Documents" دارای یک ساختار درختی چند سطحی باشد. برای نمایش ساختار درختی این دایرکتوری با محدودیت تا دو سطح، می‌توانید دستور زیر را اجرا کنید:
`$tree -L 2 /home/user/Documents`
این دستور فقط دو سطح از زیردایرکتوری‌های "/home/user/Documents" را نمایش خواهد داد.

- نمایش نام فایل‌ها در قالب سطری: با استفاده از گزینه "f-"، دستور "tree" می‌تواند نام فایل‌ها را به همراه مسیر کامل آن‌ها در یک سطر نمایش دهد.
`$tree -f

#    /work2_MehrnazShahi
#   │   ├── ./work2_MehrnazShahi/ex.sh
#   │   ├── ./work2_MehrnazShahi/info.txt
#   │   └── ./work2_MehrnazShahi/log.txt

`

- نمایش سازگار با ANSI: با استفاده از گزینه "A-"، دستور "tree" می‌تواند خروجی خود را با ANSI سازگار کند و برای چاپ یا نمایش در ترمینال بهینه شود.

---

### نحوه نصب
`$sudo apt update`
`$sudo apt install tree`
برای اطمینان از نصب دستور زیر را اجرا کنید:
`$tree --version`
---
### توضیح برخی از آپشن ها
-d: فقط دایرکتوری‌ها را لیست می‌کند.
-l: در صورتی که لینک‌های نمادین به دایرکتوری‌ها اشاره داشته باشند، آن‌ها را به عنوان دایرکتوری‌ها محاسبه می‌کند.
-f: پیشوند مسیر کامل هر فایل را چاپ می‌کند.
-x: فقط در فایل‌سیستم فعلی بمانید.
-L level: حداکثر عمق نمایش درخت دایرکتوری را تعیین می‌کند.
-R: در تمام سطوح زیردایرکتوری‌ها (مطابق با آپشن -L) را به صورت بازگشتی نمایش می‌دهد.
-P pattern: فقط فایل‌هایی که با الگوی وایلدکارد مطابقت دارند را لیست می‌کند.
-N: کاراکترهای غیرقابل چاپ را به صورت غیرقابل چاپ چاپ می‌کند.
-Q: نام فایل‌ها را در دو نقل قول چاپ می‌کند.
-p: نوع و مجوز فایل را برای هر فایل چاپ می‌کند.
-u: نام کاربری (یا شماره UID اگر نام کاربری در دسترس نباشد) را برای هر فایل چاپ می‌کند.
-g: نام گروه (یا شماره GID اگر نام گروه در دسترس نباشد) را برای هر فایل چاپ می‌کند.
-s: اندازه هر فایل را به بایت همراه با نام چاپ می‌کند.
-h: اندازه هر فایل را به صورت خوانا‌پذیرتر چاپ می‌کند.
-i: خطوط فاصله را چاپ نمی‌کند.
-A: از گرافیک خطوط ANSI برای چاپ خط‌های فاصله استفاده می‌کند.
-S: از گرافیک خطوط CP437 برای چاپ خط‌های فاصله استفاده می‌کند.
-n: همیشه رنگ‌آمیزی را خاموش می‌کند.
-C: همیشه رنگ‌آمیزی را روشن می‌کند.

</div>

---

Author or Authors:

- *[mehrnaz-shahi]* | **<mhrnzshahi@gmail.com>**

**Comment by shabane** [comment]
سلام، مجددا ممنون بابت مشارکت‌،
دستور tree توی کتاب موجود هست،‌
ولی می‌تونید با آپشن های بیشتر این فصل رو اپدیت کنید،

https://bit-orbit.github.io/the-secret-bit/tools/tree/tree/

**Comment by shabane** [comment]
چند نکته، ما نحوه نصب رو توضیح نمی‌دیم چون هر دیسترو متفاوت هست‌ش

دوم اینکه هر سوییچ رو داخل یک قسمت برای خودش قرار می‌دیم

مثلا
### نمایش فایل های مخفی

توضیحات...


### نمایش فقط دایرکتوری ها

توضیحات...
