### ISSUE TITLE
chmod

### ISSUE THREAD

**Issue by mehrnaz-shahi** [bit-orbit/TheSecretBit#67]
<div dir='rtl'>

[!["Image Alt"](img src)](Link of image)

### فهرست

> - [مقدمه](#مقدمه)
> - [اعداد دسترسی](#اعداد-دسترسی)
> -  [روش دیگر اعطای دسترسی](#روش-دیگر-اعطای-دسترسی)

---

### مقدمه
در ابتدا دستور 
$ls -l
را اجرا کنید تا مجوزهای فعلی را ببینید.
![image](https://github.com/bit-orbit/the-secret-bit/assets/91686230/c53f29c9-df03-4545-bf62-d41af637c8d0)

این دستور برای تغییر سطوح دسترسی فایل‌ها و دایرکتوری‌ها به کار می‌رود. این دستور به شما امکان می‌دهد تا سطوح دسترسی به فایل‌ها و دایرکتوری‌ها را برای کاربران مختلف تغییر دهید.

---

### اعداد دسترسی
•	r (read): 4
•	w (write): 2
•	x (execute): 1

دسترسی ها برای کاربر، گروه و سایرکاربران تعریف می شود به این صورت که ما باید سه مقدار را با عدد دسترسی پر کنیم : 
chmod - - -
اولین عدد از سمت چپ جمع اعداد دسترسی برای صاحب فایل
دومین برای دسترسی گروه صاحب فایل 
و آخرین دسترسی سایر کاربرهاست
به عنوان مثال : 
chmod 755 myfile.txt
در این مثال، سطح دسترسی فایل myfile.txt به صورت زیر تغییر می‌کند:

صاحب فایل دسترسی خواندن، نوشتن و اجرا دارد (7) = 4 + 2+ 1
گروهی که فایل در آن قرار دارد دسترسی خواندن و اجرا دارند (5) = 4 + 1
دیگر کاربران نیز دسترسی خواندن و اجرا دارند (5)

---

### روش دیگر اعطای دسترسی
Read (r)
Write (w)
Execute (x)

chmod +rwx 
chmod -rwx 
chmod +x 
chmod -wx

chmod g+w filename

chmod g-wx filename

chmod o+w filename

chmod o-rwx foldername

'+' به معنی اعطای دسترسی و - به معنی گرفتن دسترسی است.
g برای گروه
o برای سایر کاربران
u برای صاحب فایل
ugo یا a برای همه

</div>

---

Author or Authors:

- *[Mehrnaz Shahi]* | **<mhrnz@gmail.com>**

**Comment by shabane** [comment]
سلام، از اینکه داری مشارکت می‌کنی خیلی خوشحالم :)
من تا 31 این ماه امتحان دارم و خب یکم درگیرم، برسی نوشته ها برام زمان می‌بره.

اینجا باید یکم بیشتر دستور رو توضیح بدین، خیلی ساده بیان شده و خب کسی که اطلاعی نداره از chmod، این دستور رو با خوندن این فصل درک نمی‌کنه.

برای مثال پیشنهاد می‌کنم [این فصل](https://bit-orbit.github.io/the-secret-bit/tools/dd/dd/) رو بخونید و بیشتر با ساختار نوشته ها آشنا بشین:
